server:
  port: 8080

#  datasource:
#    #使用druid连接池
#    type: com.alibaba.druid.pool.DruidDataSource
#    db1:
#      jdbc-url: jdbc:mysql://127.0.0.1:3306/mytest1?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: orcl
#      driver-class-name: com.mysql.jdbc.Driver
#    db2:
#      jdbc-url: jdbc:mysql://127.0.0.1:3306/mytest2?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: orcl
#      driver-class-name: com.mysql.jdbc.Driver

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:/mappering/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.fufu.mapper
#  config-locations: classpath:mybatis/mybatis-config.xml

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

# Spring configuration
spring:
  thymeleaf:
    #开启模板缓存（默认值：true）
    cache: false
    #Check that the template exists before rendering it.
    check-template: true
    #检查模板位置是否正确（默认值:true）
    check-template-location: true
    #开启MVC Thymeleaf视图解析（默认值：true）
    enabled: true
    #模板编码
    encoding: UTF-8
    #要被排除在解析之外的视图名称列表，用逗号分隔
    spring.thymeleaf.excluded-view-names:
    #要运用于模板之上的模板模式。另见StandardTemplate-ModeHandlers(默认值：HTML5)
    mode: HTML5
    #在构建URL时添加到视图名称前的前缀（默认值：classpath:/templates/）
    prefix: classpath:/templates/
    #在构建URL时添加到视图名称后的后缀（默认值：.html）
    suffix: .html
    #Thymeleaf模板解析器在解析器链中的顺序。默认情况下，它排第一位。顺序从1开始，
    #只有在定义了额外的TemplateResolver Bean时才需要设置这个属性。
    template-resolver-order:
    #可解析的视图名称列表，用逗号分隔
    spring.thymeleaf.view-names:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  #Multi DataSource Config
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/mytest1
      username: root
      password: orcl
      driver-class-name: com.mysql.jdbc.Driver
      ###################以下为druid增加的配置###########################
      type: com.alibaba.druid.pool.DruidDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
      filters:
        commons-log.connection-logger-name: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
    slave:
      url: jdbc:mysql://localhost:3306/mytest2
      username: root
      password: orcl
      driver-class-name: com.mysql.jdbc.Driver
      ###################以下为druid增加的配置###########################
      type: com.alibaba.druid.pool.DruidDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
      filters:
        commons-log.connection-logger-name: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1
test:
  aconfig: value
#输出日志文件，默认不输出
logging:
  file: /SpringBootLog.txt
#修改日志级别，默认为INFO
  level:
    root: DEBUG



